# vim:ft=kitty

## name:     Pencil Light
## upstream: https://github.com/dexpota/kitty-themes/blob/master/themes/PencilLight.conf

# The basic colors
background #f0f0f0
foreground #414141
selection_foreground #f0f0f0
selection_background #b6d6fc

# Cursor colors
cursor #20bafb
cursor_text_color #f0f0f0

# URL underline color when hovering with mouse
url_color #008ec4

# Kitty window border colors
active_border_color #10a778
inactive_border_color #d9d9d9
bell_border_color #a79c14

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground #f0f0f0
active_tab_background #008ec4
inactive_tab_foreground #414141
inactive_tab_background #d9d9d9
tab_bar_background #e0e0e0

# The 16 terminal colors

# black
color0 #202020
color8 #414141

# red
color1 #c30670
color9 #fb0079

# green
color2  #10a778
color10 #5ed6ae

# yellow
color3  #a79c14
color11 #f3e42f

# blue
color4  #008ec4
color12 #20bafb

# magenta
color5  #523b78
color13 #6854de

# cyan
color6  #20a4b9
color14 #4fb8cc

# white
color7  #d9d9d9
color15 #f0f0f0
