# vim:ft=kitty

## name:     Monokai Pro (Filter Octagon)
## upstream: https://github.com/dexpota/kitty-themes/blob/master/themes/Monokai_Pro_(Filter_Octagon).conf

# The basic colors
background #3a3d4b
foreground #eaf2f1
selection_foreground #3a3d4b
selection_background #eaf2f1

# Cursor colors
cursor #eaf2f1
cursor_text_color #000000

# URL underline color when hovering with mouse
url_color #9cd1bb

# Kitty window border colors
active_border_color #bad761
inactive_border_color #696d77
bell_border_color #ffd76d

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground #3a3d4b
active_tab_background #bad761
inactive_tab_foreground #eaf2f1
inactive_tab_background #3a3d4b
tab_bar_background #2d2f3a

# The 16 terminal colors

# black
color0 #3a3d4b
color8 #696d77

# red
color1 #ff657a
color9 #ff657a

# green
color2  #bad761
color10 #bad761

# yellow
color3  #ffd76d
color11 #ffd76d

# blue
color4  #ff9b5e
color12 #ff9b5e

# magenta
color5  #c39ac9
color13 #c39ac9

# cyan
color6  #9cd1bb
color14 #9cd1bb

# white
color7  #eaf2f1
color15 #eaf2f1
