# vim:ft=kitty

## name:     Piatto Light
## upstream: https://github.com/dexpota/kitty-themes/blob/master/themes/Piatto_Light.conf

# The basic colors
background #ffffff
foreground #414141
selection_foreground #ffffff
selection_background #6f6a4e

# Cursor colors
cursor #5e76c7
cursor_text_color #ffffff

# URL underline color when hovering with mouse
url_color #3b5ea7

# Kitty window border colors
active_border_color #66781d
inactive_border_color #f1f1f1
bell_border_color #cc6e33

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground #ffffff
active_tab_background #3b5ea7
inactive_tab_foreground #414141
inactive_tab_background #f1f1f1
tab_bar_background #e8e8e8

# The 16 terminal colors

# black
color0 #414141
color8 #3e3e3e

# red
color1 #b23670
color9 #da3365

# green
color2  #66781d
color10 #829428

# yellow
color3  #cc6e33
color11 #cc6e33

# blue
color4  #3b5ea7
color12 #3b5ea7

# magenta
color5  #a353b2
color13 #a353b2

# cyan
color6  #66781d
color14 #829428

# white
color7  #ffffff
color15 #f1f1f1
